source "https://rubygems.org"

gem "lita"
gem "lita-slack"
gem "lita-google-images"
gem "lita-google"
#gem "lita-talk"
gem "lita-tenki", :path => "handlers/lita-tenki"
gem "lita-lanch", :path => "handlers/lita-lanch"
gem "io-console"
gem "json"
gem "lita-suddenly", :path => "handlers/lita-suddenly"
gem 'pebbles-suddenly_death_string'

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
